service: second-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.6
  eventBridge.useCloudFormation: true
  lambdaHashingVersion: 20201221
  iam:
    role: arn:aws:iam::624733648801:role/Role-serverless-function
  deploymentBucket:
    name: codebuildjuver
    serverSideEncryption: AES256
  deploymentPrefix: serverless/example


plugins:
  - serverless-deployment-bucket


functions:
  lambda1:
    handler: lambdas/restaurant1/lambda_function.lambda_handler
    package:
      patterns:
      - '!**'
      - lambdas/restaurant1/*
      - lambdas/restaurant1/model/*
      individually: true
 
  
  lambda2:
    handler: lambdas/restaurant2/lambda_function.lambda_handler
    package:
      patterns:
      - '!**'
      - lambdas/restaurant2/*
      - lambdas/restaurant2/model/*
      individually: true
    
