service: second-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.6
  eventBridge.useCloudFormation: true
  lambdaHashingVersion: 20201221
  iam:
    role: arn:aws:iam::624733648801:role/Role-serverless-function
  deploymentBucket:
    name: codebuildjuver
    serverSideEncryption: AES256
  deploymentPrefix: serverless/example


plugins:
  - serverless-deployment-bucket


functions:
  lambda1:
    handler: lambdas/restaurant1-chal/lambda_function.lambda_handler
    package:
      patterns:
      - '!**'
      - lambdas/restaurant1-chal/*
      - lambdas/restaurant1-chal/model/*
      individually: true
 
  
  lambda2:
    handler: lambdas/restaurant1-champ/lambda_function.lambda_handler
    package:
      patterns:
      - '!**'
      - lambdas/restaurant1-champ/*
      - lambdas/restaurant1-champ/model/*
      individually: true

  restaurant2-chal:
    handler: lambdas/restaurant2-chal/lambda_function.lambda_handler
    package:
      patterns:
      - '!**'
      - lambdas/restaurant2-chal/*
      - lambdas/restaurant2-chal/model/*
      individually: true
 
  
  restaurant2-champ:
    handler: lambdas/restaurant2-champ/lambda_function.lambda_handler
    package:
      patterns:
      - '!**'
      - lambdas/restaurant2-champ/*
      - lambdas/restaurant2-champ/model/*
      individually: true
    
